version: '3.8'

services:
  time-mcp-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version with hot reload
  time-mcp-dev:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    environment:
      - PORT=8080
      - ENVIRONMENT=development
      - HOST=0.0.0.0
    command: ["python", "-m", "time_mcp_server", "--http"]
    profiles:
      - dev

  # Optional: nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - time-mcp-server
    restart: unless-stopped
    profiles:
      - nginx
